apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
data:
  application-deploy.yml: |
    spring:
        cloud:
            gateway:
                routes[0]:
                    uri: {{ .Values.customerRoute.uri }}
                routes[1]:
                    uri: {{ .Values.contactRoute.uri }}