server:
  port: @service.port@

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lvoxx/SRMS-Repository
          default-label: main  # master
          clone-on-start: true
          force-pull: true

# Cấu hình Actuator (optional)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always