services:
  maildev:
    image: maildev/maildev:2.2.1
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP port
      - "1080:1080" # Web UI port
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    volumes:
      - maildev-data:/tmp/maildev
volumes:
  maildev-data: