services:
  pg-customer:
    image: postgres:14.18
    container_name: postgres-customer
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass
    volumes:
      - ./database/customer.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-customer:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - srms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customer_user -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg-customer: