server:
  port: @service.port@
  reactive:
    session:
      timeout: 30m

spring:
  application:
    name: contactor-service
  profiles:
    active: docker
  threads:
    virtual:
      enabled: true 