spring:
  cache:
    type: redis 
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/demo_db
    username: demo_user
    password: demo_pass
    pool:
      initial-size: 10
      max-size: 100            # tăng pool size cho high load
      max-idle-time: 60s
      validation-query: SELECT 1

  data:
    redis:
      host: redis
      port: 6379
      timeout: 5s
      client-type: lettuce
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          time-between-eviction-runs: 5s

  webflux:
    base-path: ""

  main:
    web-application-type: reactive

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: KEBAB_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    time-zone: Asia/Ho_Chi_Minh

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}