/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.lvoxx.srms.kafka.warehouse;
@org.apache.avro.specific.AvroGenerated
public enum AlertLevel implements org.apache.avro.generic.GenericEnumSymbol<AlertLevel> {
  WARNING, CRITICAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertLevel\",\"namespace\":\"io.github.lvoxx.srms.kafka.warehouse\",\"symbols\":[\"WARNING\",\"CRITICAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
