/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.lvoxx.srms.kafka.warehouse;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

/** Warehouse's product alert message with threshold for monitoring */
@org.apache.avro.specific.AvroGenerated
public class WarehouseAlertMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8095629124301331534L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WarehouseAlertMessage\",\"namespace\":\"io.github.lvoxx.srms.kafka.warehouse\",\"doc\":\"Warehouse's product alert message with threshold for monitoring\",\"fields\":[{\"name\":\"messageId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier for the alert message\"},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier of the product\"},{\"name\":\"productName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the product\"},{\"name\":\"currentQuantity\",\"type\":\"int\",\"doc\":\"Current quantity in warehouse inventory\"},{\"name\":\"threshold\",\"type\":\"int\",\"doc\":\"Threshold value that triggers the alert\"},{\"name\":\"level\",\"type\":{\"type\":\"enum\",\"name\":\"AlertLevel\",\"symbols\":[\"WARNING\",\"CRITICAL\"]},\"doc\":\"Severity level of the alert\"},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Human readable alert message\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Timestamp when the alert was created in milliseconds\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WarehouseAlertMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WarehouseAlertMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WarehouseAlertMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WarehouseAlertMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WarehouseAlertMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WarehouseAlertMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WarehouseAlertMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WarehouseAlertMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WarehouseAlertMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the alert message */
  private java.lang.String messageId;
  /** Unique identifier of the product */
  private java.lang.String productId;
  /** Name of the product */
  private java.lang.String productName;
  /** Current quantity in warehouse inventory */
  private int currentQuantity;
  /** Threshold value that triggers the alert */
  private int threshold;
  /** Severity level of the alert */
  private io.github.lvoxx.srms.kafka.warehouse.AlertLevel level;
  /** Human readable alert message */
  private java.lang.String message;
  /** Timestamp when the alert was created in milliseconds */
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WarehouseAlertMessage() {}

  /**
   * All-args constructor.
   * @param messageId Unique identifier for the alert message
   * @param productId Unique identifier of the product
   * @param productName Name of the product
   * @param currentQuantity Current quantity in warehouse inventory
   * @param threshold Threshold value that triggers the alert
   * @param level Severity level of the alert
   * @param message Human readable alert message
   * @param timestamp Timestamp when the alert was created in milliseconds
   */
  public WarehouseAlertMessage(java.lang.String messageId, java.lang.String productId, java.lang.String productName, java.lang.Integer currentQuantity, java.lang.Integer threshold, io.github.lvoxx.srms.kafka.warehouse.AlertLevel level, java.lang.String message, java.lang.Long timestamp) {
    this.messageId = messageId;
    this.productId = productId;
    this.productName = productName;
    this.currentQuantity = currentQuantity;
    this.threshold = threshold;
    this.level = level;
    this.message = message;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageId;
    case 1: return productId;
    case 2: return productName;
    case 3: return currentQuantity;
    case 4: return threshold;
    case 5: return level;
    case 6: return message;
    case 7: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageId = value$ != null ? value$.toString() : null; break;
    case 1: productId = value$ != null ? value$.toString() : null; break;
    case 2: productName = value$ != null ? value$.toString() : null; break;
    case 3: currentQuantity = (java.lang.Integer)value$; break;
    case 4: threshold = (java.lang.Integer)value$; break;
    case 5: level = (io.github.lvoxx.srms.kafka.warehouse.AlertLevel)value$; break;
    case 6: message = value$ != null ? value$.toString() : null; break;
    case 7: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'messageId' field.
   * @return Unique identifier for the alert message
   */
  public java.lang.String getMessageId() {
    return messageId;
  }


  /**
   * Sets the value of the 'messageId' field.
   * Unique identifier for the alert message
   * @param value the value to set.
   */
  public void setMessageId(java.lang.String value) {
    this.messageId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return Unique identifier of the product
   */
  public java.lang.String getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * Unique identifier of the product
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return Name of the product
   */
  public java.lang.String getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * Name of the product
   * @param value the value to set.
   */
  public void setProductName(java.lang.String value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'currentQuantity' field.
   * @return Current quantity in warehouse inventory
   */
  public int getCurrentQuantity() {
    return currentQuantity;
  }


  /**
   * Sets the value of the 'currentQuantity' field.
   * Current quantity in warehouse inventory
   * @param value the value to set.
   */
  public void setCurrentQuantity(int value) {
    this.currentQuantity = value;
  }

  /**
   * Gets the value of the 'threshold' field.
   * @return Threshold value that triggers the alert
   */
  public int getThreshold() {
    return threshold;
  }


  /**
   * Sets the value of the 'threshold' field.
   * Threshold value that triggers the alert
   * @param value the value to set.
   */
  public void setThreshold(int value) {
    this.threshold = value;
  }

  /**
   * Gets the value of the 'level' field.
   * @return Severity level of the alert
   */
  public io.github.lvoxx.srms.kafka.warehouse.AlertLevel getLevel() {
    return level;
  }


  /**
   * Sets the value of the 'level' field.
   * Severity level of the alert
   * @param value the value to set.
   */
  public void setLevel(io.github.lvoxx.srms.kafka.warehouse.AlertLevel value) {
    this.level = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return Human readable alert message
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * Human readable alert message
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Timestamp when the alert was created in milliseconds
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Timestamp when the alert was created in milliseconds
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new WarehouseAlertMessage RecordBuilder.
   * @return A new WarehouseAlertMessage RecordBuilder
   */
  public static io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder newBuilder() {
    return new io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder();
  }

  /**
   * Creates a new WarehouseAlertMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WarehouseAlertMessage RecordBuilder
   */
  public static io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder newBuilder(io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder other) {
    if (other == null) {
      return new io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder();
    } else {
      return new io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder(other);
    }
  }

  /**
   * Creates a new WarehouseAlertMessage RecordBuilder by copying an existing WarehouseAlertMessage instance.
   * @param other The existing instance to copy.
   * @return A new WarehouseAlertMessage RecordBuilder
   */
  public static io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder newBuilder(io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage other) {
    if (other == null) {
      return new io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder();
    } else {
      return new io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for WarehouseAlertMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WarehouseAlertMessage>
    implements org.apache.avro.data.RecordBuilder<WarehouseAlertMessage> {

    /** Unique identifier for the alert message */
    private java.lang.String messageId;
    /** Unique identifier of the product */
    private java.lang.String productId;
    /** Name of the product */
    private java.lang.String productName;
    /** Current quantity in warehouse inventory */
    private int currentQuantity;
    /** Threshold value that triggers the alert */
    private int threshold;
    /** Severity level of the alert */
    private io.github.lvoxx.srms.kafka.warehouse.AlertLevel level;
    /** Human readable alert message */
    private java.lang.String message;
    /** Timestamp when the alert was created in milliseconds */
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageId)) {
        this.messageId = data().deepCopy(fields()[0].schema(), other.messageId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.currentQuantity)) {
        this.currentQuantity = data().deepCopy(fields()[3].schema(), other.currentQuantity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.threshold)) {
        this.threshold = data().deepCopy(fields()[4].schema(), other.threshold);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.level)) {
        this.level = data().deepCopy(fields()[5].schema(), other.level);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.message)) {
        this.message = data().deepCopy(fields()[6].schema(), other.message);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing WarehouseAlertMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.messageId)) {
        this.messageId = data().deepCopy(fields()[0].schema(), other.messageId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.currentQuantity)) {
        this.currentQuantity = data().deepCopy(fields()[3].schema(), other.currentQuantity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.threshold)) {
        this.threshold = data().deepCopy(fields()[4].schema(), other.threshold);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.level)) {
        this.level = data().deepCopy(fields()[5].schema(), other.level);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.message)) {
        this.message = data().deepCopy(fields()[6].schema(), other.message);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'messageId' field.
      * Unique identifier for the alert message
      * @return The value.
      */
    public java.lang.String getMessageId() {
      return messageId;
    }


    /**
      * Sets the value of the 'messageId' field.
      * Unique identifier for the alert message
      * @param value The value of 'messageId'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setMessageId(java.lang.String value) {
      validate(fields()[0], value);
      this.messageId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messageId' field has been set.
      * Unique identifier for the alert message
      * @return True if the 'messageId' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messageId' field.
      * Unique identifier for the alert message
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearMessageId() {
      messageId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * Unique identifier of the product
      * @return The value.
      */
    public java.lang.String getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * Unique identifier of the product
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setProductId(java.lang.String value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * Unique identifier of the product
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * Unique identifier of the product
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * Name of the product
      * @return The value.
      */
    public java.lang.String getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * Name of the product
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setProductName(java.lang.String value) {
      validate(fields()[2], value);
      this.productName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * Name of the product
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productName' field.
      * Name of the product
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'currentQuantity' field.
      * Current quantity in warehouse inventory
      * @return The value.
      */
    public int getCurrentQuantity() {
      return currentQuantity;
    }


    /**
      * Sets the value of the 'currentQuantity' field.
      * Current quantity in warehouse inventory
      * @param value The value of 'currentQuantity'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setCurrentQuantity(int value) {
      validate(fields()[3], value);
      this.currentQuantity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'currentQuantity' field has been set.
      * Current quantity in warehouse inventory
      * @return True if the 'currentQuantity' field has been set, false otherwise.
      */
    public boolean hasCurrentQuantity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'currentQuantity' field.
      * Current quantity in warehouse inventory
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearCurrentQuantity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'threshold' field.
      * Threshold value that triggers the alert
      * @return The value.
      */
    public int getThreshold() {
      return threshold;
    }


    /**
      * Sets the value of the 'threshold' field.
      * Threshold value that triggers the alert
      * @param value The value of 'threshold'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setThreshold(int value) {
      validate(fields()[4], value);
      this.threshold = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'threshold' field has been set.
      * Threshold value that triggers the alert
      * @return True if the 'threshold' field has been set, false otherwise.
      */
    public boolean hasThreshold() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'threshold' field.
      * Threshold value that triggers the alert
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearThreshold() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'level' field.
      * Severity level of the alert
      * @return The value.
      */
    public io.github.lvoxx.srms.kafka.warehouse.AlertLevel getLevel() {
      return level;
    }


    /**
      * Sets the value of the 'level' field.
      * Severity level of the alert
      * @param value The value of 'level'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setLevel(io.github.lvoxx.srms.kafka.warehouse.AlertLevel value) {
      validate(fields()[5], value);
      this.level = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'level' field has been set.
      * Severity level of the alert
      * @return True if the 'level' field has been set, false otherwise.
      */
    public boolean hasLevel() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'level' field.
      * Severity level of the alert
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearLevel() {
      level = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * Human readable alert message
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * Human readable alert message
      * @param value The value of 'message'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setMessage(java.lang.String value) {
      validate(fields()[6], value);
      this.message = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * Human readable alert message
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'message' field.
      * Human readable alert message
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearMessage() {
      message = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Timestamp when the alert was created in milliseconds
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Timestamp when the alert was created in milliseconds
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder setTimestamp(long value) {
      validate(fields()[7], value);
      this.timestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Timestamp when the alert was created in milliseconds
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Timestamp when the alert was created in milliseconds
      * @return This builder.
      */
    public io.github.lvoxx.srms.kafka.warehouse.WarehouseAlertMessage.Builder clearTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WarehouseAlertMessage build() {
      try {
        WarehouseAlertMessage record = new WarehouseAlertMessage();
        record.messageId = fieldSetFlags()[0] ? this.messageId : (java.lang.String) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.String) defaultValue(fields()[1]);
        record.productName = fieldSetFlags()[2] ? this.productName : (java.lang.String) defaultValue(fields()[2]);
        record.currentQuantity = fieldSetFlags()[3] ? this.currentQuantity : (java.lang.Integer) defaultValue(fields()[3]);
        record.threshold = fieldSetFlags()[4] ? this.threshold : (java.lang.Integer) defaultValue(fields()[4]);
        record.level = fieldSetFlags()[5] ? this.level : (io.github.lvoxx.srms.kafka.warehouse.AlertLevel) defaultValue(fields()[5]);
        record.message = fieldSetFlags()[6] ? this.message : (java.lang.String) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WarehouseAlertMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<WarehouseAlertMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WarehouseAlertMessage>
    READER$ = (org.apache.avro.io.DatumReader<WarehouseAlertMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.messageId);

    out.writeString(this.productId);

    out.writeString(this.productName);

    out.writeInt(this.currentQuantity);

    out.writeInt(this.threshold);

    out.writeEnum(this.level.ordinal());

    out.writeString(this.message);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.messageId = in.readString();

      this.productId = in.readString();

      this.productName = in.readString();

      this.currentQuantity = in.readInt();

      this.threshold = in.readInt();

      this.level = io.github.lvoxx.srms.kafka.warehouse.AlertLevel.values()[in.readEnum()];

      this.message = in.readString();

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.messageId = in.readString();
          break;

        case 1:
          this.productId = in.readString();
          break;

        case 2:
          this.productName = in.readString();
          break;

        case 3:
          this.currentQuantity = in.readInt();
          break;

        case 4:
          this.threshold = in.readInt();
          break;

        case 5:
          this.level = io.github.lvoxx.srms.kafka.warehouse.AlertLevel.values()[in.readEnum()];
          break;

        case 6:
          this.message = in.readString();
          break;

        case 7:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










